package es.lardevpro.spring.mvc;


import java.util.HashSet;
import java.util.Set;

public class CountryOptions {
	
	 public static Set<String> getCountryOptions() {
	        
		 Set<String> countries = new HashSet<String>();

	        countries.add("Afganistán");
	        countries.add("Albania");
	        countries.add("Argelia");
	        countries.add("Andorra");
	        countries.add("Angola");
	        countries.add("Antigua y Barbuda");
	        countries.add("Argentina");
	        countries.add("Armenia");
	        countries.add("Australia");
	        countries.add("Austria");
	        countries.add("Azerbaiyán");
	        countries.add("Bahamas");
	        countries.add("Bahréin");
	        countries.add("Bangladés");
	        countries.add("Barbados");
	        countries.add("Bélgica");
	        countries.add("Belice");
	        countries.add("Benín");
	        countries.add("Bielorrusia");
	        countries.add("Birmania");
	        countries.add("Botsuana");
	        countries.add("Brasil");
	        countries.add("Brunéi");
	        countries.add("Bulgaria");
	        countries.add("Burkina Faso");
	        countries.add("Burundi");
	        countries.add("Bután");
	        countries.add("Cabo Verde");
	        countries.add("Camboya");
	        countries.add("Camerún");
	        countries.add("Canadá");
	        countries.add("Catar");
	        countries.add("Chile");
	        countries.add("China");
	        countries.add("Chipre");
	        countries.add("Colombia");
	        countries.add("Comoras");
	        countries.add("Congo");
	        countries.add("Corea del Norte");
	        countries.add("Corea del Sur");
	        countries.add("Costa Rica");
	        countries.add("Croacia");
	        countries.add("Cuba");
	        countries.add("Dinamarca");
	        countries.add("Dominica");
	        countries.add("Ecuador");
	        countries.add("Egipto");
	        countries.add("El Salvador");
	        countries.add("Emiratos Árabes Unidos");
	        countries.add("Eritrea");
	        countries.add("Eslovaquia");
	        countries.add("Eslovenia");
	        countries.add("España");
	        countries.add("Estados Unidos");
	        countries.add("Etiopía");
	        countries.add("Fiji");
	        countries.add("Filipinas");
	        countries.add("Finlandia");
	        countries.add("Francia");
	        countries.add("Gabón");
	        countries.add("Gambia");
	        countries.add("Georgia");
	        countries.add("Ghana");
	        countries.add("Granada");
	        countries.add("Guatemala");
	        countries.add("Guyana");
	        countries.add("Guinea");
	        countries.add("Guinea-Bisáu");
	        countries.add("Haití");
	        countries.add("Honduras");
	        countries.add("Hungría");
	        countries.add("India");
	        countries.add("Indonesia");
	        countries.add("Irak");
	        countries.add("Irán");
	        countries.add("Irlanda");
	        countries.add("Islandia");
	        countries.add("Israel");
	        countries.add("Italia");
	        countries.add("Jamaica");
	        countries.add("Japón");
	        countries.add("Jordania");
	        countries.add("Kazajistán");
	        countries.add("Kenia");
	        countries.add("Kirguistán");
	        countries.add("Kiribati");
	        countries.add("Kuwait");
	        countries.add("Laos");
	        countries.add("Lesoto");
	        countries.add("Letonia");
	        countries.add("Líbano");
	        countries.add("Liberia");
	        countries.add("Libia");
	        countries.add("Liechtenstein");
	        countries.add("Lituania");
	        countries.add("Luxemburgo");
	        countries.add("Madagascar");
	        countries.add("Malasia");
	        countries.add("Malaui");
	        countries.add("Maldivas");
	        countries.add("Malí");
	        countries.add("Malta");
	        countries.add("Marruecos");
	        countries.add("Mauricio");
	        countries.add("Mauritania");
	        countries.add("México");
	        countries.add("Micronesia");
	        countries.add("Moldavia");
	        countries.add("Mónaco");
	        countries.add("Mongolia");
	        countries.add("Mozambique");
	        countries.add("Namibia");
	        countries.add("Nauru");
	        countries.add("Nepal");
	        countries.add("Nicaragua");
	        countries.add("Níger");
	        countries.add("Nigeria");
	        countries.add("Noruega");
	        countries.add("Nueva Zelanda");
	        countries.add("Níger");
	        countries.add("Omán");
	        countries.add("Pakistán");
	        countries.add("Palaos");
	        countries.add("Panamá");
	        countries.add("Papúa Nueva Guinea");
	        countries.add("Paraguay");
	        countries.add("Perú");
	        countries.add("Polonia");
	        countries.add("Portugal");
	        countries.add("Reino Unido");
	        countries.add("República Checa");
	        countries.add("República Dominicana");
	        countries.add("Ruanda");
	        countries.add("Rumanía");
	        countries.add("Samoa");
	        countries.add("San Cristóbal y Nieves");
	        countries.add("San Marino");
	        countries.add("San Vicente y las Granadinas");
	        countries.add("Santa Lucía");
	        countries.add("Senegal");
	        countries.add("Serbia");
	        countries.add("Seychelles");
	        countries.add("Sierra Leona");
	        countries.add("Singapur");
	        countries.add("Siria");
	        countries.add("Somalia");
	        countries.add("Sri Lanka");
	        countries.add("Sudáfrica");
	        countries.add("Sudán");
	        countries.add("Suecia");
	        countries.add("Suiza");
	        countries.add("Surinam");
	        countries.add("Tailandia");
	        countries.add("Tanzania");
	        countries.add("Tayikistán");
	        countries.add("Timor Oriental");
	        countries.add("Togo");
	        countries.add("Tonga");
	        countries.add("Trinidad y Tobago");
	        countries.add("Túnez");
	        countries.add("Turkmenistán");
	        countries.add("Turquía");
	        countries.add("Tuvalu");
	        countries.add("Uganda");
	        countries.add("Ucrania");
	        countries.add("Uruguay");
	        countries.add("Vanuatu");
	        countries.add("Vaticano");
	        countries.add("Venezuela");
	        countries.add("Vietnam");
	        countries.add("Yemen");
	        countries.add("Yugoslavia");
	        countries.add("Zambia");
	        countries.add("Zimbabue");
	        
	        return countries;
	    }

}
